// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
    using Coherence.ProtocolDef;
    using Coherence.Serializer;
    using Coherence.Brook;
    using Coherence.Entities;
    using Coherence.Log;
    using Coherence.Core;
    using Coherence.Connection;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;
    using System;
    using UnityEngine;

    public struct _893829c7e6cfd85408e600884d32ee35 : IEntityInput, IEquatable<_893829c7e6cfd85408e600884d32ee35>
    {
        [StructLayout(LayoutKind.Explicit)]
        public struct Interop
        {
            [FieldOffset(0)]
            public System.Int32 Move;
            [FieldOffset(4)]
            public System.Byte Light;
            [FieldOffset(5)]
            public System.Byte Medium;
            [FieldOffset(6)]
            public System.Byte Heavy;
        }

        public static unsafe _893829c7e6cfd85408e600884d32ee35 FromInterop(System.IntPtr data, System.Int32 dataSize)
        {
            if (dataSize != 7) {
                throw new System.Exception($"Given data size is not equal to the struct size. ({dataSize} != 7) " +
                    "for input with ID 0");
            }

            var orig = new _893829c7e6cfd85408e600884d32ee35();
            var comp = (Interop*)data;
            orig.Move = comp->Move;
            orig.Light = comp->Light != 0;
            orig.Medium = comp->Medium != 0;
            orig.Heavy = comp->Heavy != 0;
            return orig;
        }

        public uint GetComponentType() => 0;

        public Entity Entity { get; set; }
        public Coherence.ChannelID ChannelID { get; set; }
        public MessageTarget Routing { get; set; }
        public uint SenderParticipant { get; set; }
        public ClientID SenderClientID { get; set; }
        public long Frame { get; set; }
        private bool isRemoteInput;

        public System.Int32 Move;
        public System.Boolean Light;
        public System.Boolean Medium;
        public System.Boolean Heavy;

        public _893829c7e6cfd85408e600884d32ee35(
        Entity entity,
        long frame,
        System.Int32 Move,
        System.Boolean Light,
        System.Boolean Medium,
        System.Boolean Heavy,
        bool isRemoteInput)
        {
            this.Entity = entity;
            this.ChannelID = Coherence.ChannelID.Default;
            this.Routing = MessageTarget.All;
            this.SenderParticipant = 0;
            this.SenderClientID = default;
            this.Frame = frame;
            this.isRemoteInput = isRemoteInput;
            this.Move = Move;
            this.Light = Light;
            this.Medium = Medium;
            this.Heavy = Heavy;
        }

        public override string ToString()
        {
            return $"Entity: {Entity}, Frame: {Frame}, Inputs: [Move:{Move}, Light:{Light}, Medium:{Medium}, Heavy:{Heavy}]";
        }

        public IEntityMessage Clone()
        {
            // This is a struct, so we can safely return
            // a struct copy.
            return this;
        }

        public IEntityMapper.Error MapToAbsolute(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToAbsoluteEntity(Entity, false, out var absoluteEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = absoluteEntity;
            return IEntityMapper.Error.None;
        }

        public IEntityMapper.Error MapToRelative(IEntityMapper mapper, Coherence.Log.Logger logger)
        {
            var err = mapper.MapToRelativeEntity(Entity, false, out var relativeEntity);
            if (err != IEntityMapper.Error.None)
            {
                return err;
            }
            Entity = relativeEntity;
            return IEntityMapper.Error.None;
        }

        public HashSet<Entity> GetEntityRefs() => default;

        public void NullEntityRefs(Entity entity) { }

        public bool Equals(_893829c7e6cfd85408e600884d32ee35 other)
        {
            return
                this.Move == other.Move&&
                this.Light == other.Light&&
                this.Medium == other.Medium&&
                this.Heavy == other.Heavy;
        }

        public static void Serialize(_893829c7e6cfd85408e600884d32ee35 inputData, IOutProtocolBitStream bitStream)
        {
            bitStream.WriteIntegerRange(inputData.Move, 32, -2147483648);
            bitStream.WriteBool(inputData.Light);
            bitStream.WriteBool(inputData.Medium);
            bitStream.WriteBool(inputData.Heavy);
        }

        public static _893829c7e6cfd85408e600884d32ee35 Deserialize(IInProtocolBitStream bitStream, Entity entity, long frame)
        {
            var dataMove = bitStream.ReadIntegerRange(32, -2147483648);
            var dataLight = bitStream.ReadBool();
            var dataMedium = bitStream.ReadBool();
            var dataHeavy = bitStream.ReadBool();

            return new _893829c7e6cfd85408e600884d32ee35()
            {
                Entity = entity,
                Frame = frame,
                Move = dataMove,
                Light = dataLight,
                Medium = dataMedium,
                Heavy = dataHeavy,
                isRemoteInput = true
            };
        }
    }

}
